name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

jobs:
  test:
    strategy:
      matrix:
        crystal: [1.0.x, 1.1.x, 1.2.x]
    runs-on: ubuntu-latest
    steps:
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run specs
        run: crystal spec
      - name: Check formatting
        run: crystal tool format --check
